#!/usr/bin/env python3
"""Generate a fixed-origin Homebrew formula from verified local release archives."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import stat
import sys
import tarfile

TARGETS = (("darwin", "amd64"), ("darwin", "arm64"), ("linux", "amd64"), ("linux", "arm64"))
ORIGIN = "https://github.com/LanceSandino/aws-sso-profile-sync"
SEMVER = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?\Z", re.ASCII)


def regular(path):
    if not stat.S_ISREG(path.lstat().st_mode):
        raise ValueError(f"expected regular file: {path.name}")


def digest(file):
    file.seek(0)
    sha = hashlib.sha256()
    for chunk in iter(lambda: file.read(1024 * 1024), b""):
        sha.update(chunk)
    return sha.hexdigest()


def release_inputs(version_file, dist):
    regular(version_file)
    version = version_file.read_text().strip()
    match = SEMVER.fullmatch(version)
    if not match or (match.group(4) and any(part.isdigit() and len(part) > 1 and part.startswith("0")
                                           for part in match.group(4).split("."))):
        raise ValueError("VERSION must contain one canonical SemVer")
    expected = {f"aws-sso-profile-sync_{version}_{os_name}_{arch}.tar.gz": f"{os_name}/{arch}"
                for os_name, arch in TARGETS}
    sums = dist / "SHA256SUMS"
    regular(sums)
    checksums = {}
    for line in sums.read_text().splitlines():
        match = re.fullmatch(r"([0-9a-f]{64})  (.+)", line)
        if not match:
            raise ValueError("invalid SHA256SUMS entry")
        sha, name = match.groups()
        if name not in expected:
            raise ValueError("unexpected archive in SHA256SUMS")
        if name in checksums:
            raise ValueError("duplicate archive in SHA256SUMS")
        checksums[name] = sha
    if set(checksums) != set(expected):
        raise ValueError("SHA256SUMS must contain all four target archives")
    for name, target in expected.items():
        path = dist / name
        regular(path)
        with path.open("rb") as file:
            if digest(file) != checksums[name]:
                raise ValueError(f"checksum mismatch: {name}")
            file.seek(0)
            with tarfile.open(fileobj=file, mode="r:gz") as archive:
                prefix = name[:-7] + "/"
                member = archive.getmember(prefix + "BUILD-METADATA.json")
                if not member.isfile() or member.size > 65536:
                    raise ValueError("invalid archive metadata")
                metadata = json.load(archive.extractfile(member))
                if metadata.get("version") != version or metadata.get("target") != target:
                    raise ValueError("archive metadata mismatch")
                for required in ("aws-sso-profile-sync", "LICENSE", "NOTICE", "THIRD_PARTY_NOTICES.md"):
                    if not archive.getmember(prefix + required).isfile():
                        raise ValueError(f"missing archive payload: {required}")
            if digest(file) != checksums[name]:
                raise ValueError(f"archive changed during validation: {name}")
    return version, checksums


def formula(version, checksums):
    def target(os_name, arch):
        name = f"aws-sso-profile-sync_{version}_{os_name}_{arch}.tar.gz"
        return (f'      url "{ORIGIN}/releases/download/v{version}/{name}"\n'
                f'      sha256 "{checksums[name]}"')
    return f'''# Generated by scripts/homebrew.py from verified release archives.
class AwsSsoProfileSync < Formula
  desc "Safely discover and synchronize AWS IAM Identity Center profiles"
  homepage "{ORIGIN}"
  version "{version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
{target("darwin", "arm64")}
    end
    on_intel do
{target("darwin", "amd64")}
    end
  end

  on_linux do
    on_arm do
{target("linux", "arm64")}
    end
    on_intel do
{target("linux", "amd64")}
    end
  end

  def install
    bin.install "aws-sso-profile-sync"
    pkgshare.install "LICENSE", "NOTICE", "THIRD_PARTY_NOTICES.md"
  end

  test do
    require "json"
    require "shellwords"
    ENV.keys.grep(/^AWS_/).each {{ |key| ENV.delete(key) }}
    home = testpath/"isolated-home"
    home.mkpath
    ENV["HOME"] = home.to_s
    ENV["AWS_CONFIG_FILE"] = (home/".aws/config").to_s
    ENV["AWS_SHARED_CREDENTIALS_FILE"] = (home/".aws/credentials").to_s
    ENV["AWS_EC2_METADATA_DISABLED"] = "true"
    ENV["NO_COLOR"] = "1"
    executable = (bin/"aws-sso-profile-sync").to_s.shellescape
    config = (home/".aws/config").to_s.shellescape
    state = (home/".aws-sso-profile-sync").to_s.shellescape
    assert_equal version.to_s, shell_output("#{{executable}} --version").strip
    command = "#{{executable}} doctor --format json --config-file #{{config}} --state-dir #{{state}}"
    result = JSON.parse(shell_output(command))
    assert_equal 1, result.fetch("schema_version")
    assert_equal "doctor", result.fetch("command")
    assert_equal "ok", result.fetch("status")
    refute_path_exists home/".aws/config"
    refute_path_exists home/".aws-sso-profile-sync"
  end
end
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version-file", type=Path, default=Path("VERSION"))
    parser.add_argument("--dist-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        version, checksums = release_inputs(args.version_file, args.dist_dir)
        output = formula(version, checksums)
        if args.output.is_symlink():
            raise ValueError("formula output must not be a symlink")
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output)
    except (OSError, ValueError, KeyError, tarfile.TarError) as error:
        print(f"Homebrew generation failed: {error}", file=sys.stderr)
        return 1
    print(f"Generated {args.output.name} for {version}; release publication remains owner-controlled")
    return 0


if __name__ == "__main__":
    sys.exit(main())
