#!/usr/bin/env python3
"""Validate one-source versions and fail-closed owner release acceptance metadata."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile

ACCEPTANCE_PATH = ".github/release-acceptance.json"
R_CASES = {f"R{i:02d}" for i in range(1, 10)}
SEMVER = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?", re.ASCII)

class ReleaseError(Exception):
    """Actionable metadata failures; never include document bodies or secrets."""

def semver(value):
    if not isinstance(value, str):
        raise ReleaseError("VERSION must be a SemVer string")
    match = SEMVER.fullmatch(value)
    if not match:
        raise ReleaseError("invalid SemVer; use major.minor.patch with optional prerelease/build")
    if match.group(4):
        for identifier in match.group(4).split("."):
            if identifier.isdigit() and len(identifier) > 1 and identifier.startswith("0"):
                raise ReleaseError("numeric SemVer prerelease identifiers cannot have leading zeros")
    return value

def read_version(root):
    try:
        text = (root / "VERSION").read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        raise ReleaseError("cannot read repository VERSION") from None
    value = text.removesuffix("\n")
    semver(value)
    if text != value + "\n":
        raise ReleaseError("VERSION must contain exactly one version and final newline")
    return value

def generated_default(version):
    return '// Code generated by scripts/release.py check --write; DO NOT EDIT.\n\npackage cli\n\nvar Version = "' + version + '"\n'

def check_default(root, write=False):
    version = read_version(root)
    target = root / "internal" / "cli" / "version.go"
    expected = generated_default(version)
    if write:
        for path in [target, *target.parents]:
            if path.is_symlink():
                raise ReleaseError("refusing a symlink in generated version path")
            if path == root:
                break
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            descriptor, temporary = tempfile.mkstemp(prefix=".version-", dir=target.parent)
            try:
                with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as output:
                    output.write(expected)
                    output.flush()
                    os.fsync(output.fileno())
                os.chmod(temporary, 0o644)
                os.replace(temporary, target)
            finally:
                if os.path.exists(temporary):
                    os.unlink(temporary)
        except OSError:
            raise ReleaseError("cannot generate Go version default") from None
    try:
        actual = target.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        raise ReleaseError("generated Go version missing; run release.py check --write") from None
    if actual != expected:
        raise ReleaseError("generated Go version is stale; run release.py check --write")
    return version

def git(root, *args):
    try:
        return subprocess.check_output(["git", "-C", str(root), *args], stderr=subprocess.DEVNULL, timeout=15)
    except (OSError, subprocess.SubprocessError):
        raise ReleaseError("release fingerprint requires a readable Git repository") from None

def untracked_release_input(path):
    parts = Path(os.fsdecode(path)).parts
    if not parts or path == ACCEPTANCE_PATH.encode() or parts[0] in {"dist", ".venv", ".pytest_cache"} or "__pycache__" in parts:
        return False
    return parts[0] in {"cmd", "internal", "scripts", ".github", "docs", "testdata", "tests", "quality", "packaging", "vendor"} or parts[-1] in {"VERSION", "LICENSE", "NOTICE", "go.mod", "go.sum", "go.work", "go.work.sum", ".gitignore", ".gitattributes", ".gitmodules"} or Path(parts[-1]).suffix in {".go", ".py", ".sh", ".md", ".json", ".yml", ".yaml", ".s", ".S", ".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".f", ".F", ".for", ".f90", ".m", ".syso"}

def require_tracked_inputs(root):
    for path in git(root, "ls-files", "--others", "-z").split(b"\0"):
        if untracked_release_input(path):
            raise ReleaseError("untracked release source input; add reviewed inputs to Git before fingerprinting")

def require_clean_baseline(root):
    try:
        probe = subprocess.run(["git", "-C", str(root), "rev-parse", "--verify", "--quiet", "HEAD"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=15)
    except (OSError, subprocess.SubprocessError):
        raise ReleaseError("cannot inspect committed source baseline") from None
    if probe.returncode != 0:
        raise ReleaseError("release gate requires a committed source baseline")
    changed = git(root, "diff", "--name-only", "-z", "HEAD", "--")
    if any(path and path != ACCEPTANCE_PATH.encode() for path in changed.split(b"\0")):
        raise ReleaseError("tracked source differs from committed baseline; only acceptance-record edits are permitted")

def fingerprint(root):
    try:
        top = Path(os.fsdecode(git(root, "rev-parse", "--show-toplevel").strip())).resolve()
    except (ValueError, OSError):
        raise ReleaseError("cannot resolve Git repository root") from None
    if top != root:
        raise ReleaseError("--root must be the Git repository root")
    require_tracked_inputs(root)
    records = git(root, "ls-files", "--stage", "-z").split(b"\0")
    digest = hashlib.sha256(b"aws-sso-profile-sync-tracked-tree-v1\0")
    selected = 0
    for record in sorted((r for r in records if r), key=lambda item: item.split(b"\t", 1)[1]):
        metadata, path = record.split(b"\t", 1)
        mode, _, stage = metadata.split(b" ")
        if stage != b"0":
            raise ReleaseError("unmerged Git index cannot be fingerprinted")
        if path == ACCEPTANCE_PATH.encode():
            continue
        relative = Path(os.fsdecode(path))
        if relative.is_absolute() or ".." in relative.parts or mode not in (b"100644", b"100755"):
            raise ReleaseError("unsupported tracked source entry; links/submodules are not release inputs")
        target = root / relative
        try:
            info = target.lstat()
            if not stat.S_ISREG(info.st_mode) or any(parent.is_symlink() for parent in target.parents if parent != root and root in parent.parents):
                raise ReleaseError("tracked source file is not a regular file")
            content = target.read_bytes()
        except OSError:
            raise ReleaseError("tracked source file is missing or unreadable") from None
        actual_mode = b"100755" if info.st_mode & 0o111 else b"100644"
        digest.update(len(path).to_bytes(8, "big"))
        digest.update(path)
        digest.update(actual_mode)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(hashlib.sha256(content).digest())
        selected += 1
    if not selected:
        raise ReleaseError("no tracked source files selected")
    return "sha256:" + digest.hexdigest()

def unique_object(pairs):
    value = {}
    for key, item in pairs:
        if key in value:
            raise ReleaseError("duplicate keys in release acceptance JSON")
        value[key] = item
    return value

def reject_constant(_):
    raise ReleaseError("nonstandard constants in release acceptance JSON")

def gate(root, acceptance=None):
    version = check_default(root)
    path = Path(acceptance) if acceptance else root / ACCEPTANCE_PATH
    if not path.is_absolute():
        path = root / path
    try:
        if path.stat().st_size > 1024 * 1024:
            raise ReleaseError("release acceptance JSON exceeds size limit")
        record = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique_object, parse_constant=reject_constant)
    except (OSError, UnicodeError, json.JSONDecodeError):
        raise ReleaseError("release acceptance record missing or malformed; real AWS remains pending") from None
    if not isinstance(record, dict) or type(record.get("schema_version")) is not int or record["schema_version"] != 1:
        raise ReleaseError("release acceptance requires JSON schema_version 1")
    if record.get("status") != "PASS":
        raise ReleaseError("release acceptance is pending; publication is blocked")
    if semver(record.get("version")) != version:
        raise ReleaseError("release acceptance version does not match VERSION")
    if record.get("source_fingerprint") != fingerprint(root):
        raise ReleaseError("release acceptance source fingerprint is stale or missing")
    require_clean_baseline(root)
    results = record.get("real_aws_acceptance")
    if not isinstance(results, dict) or set(results) != R_CASES or any(value != "PASS" for value in results.values()):
        raise ReleaseError("all nine owner-run R01-R09 results must be PASS before publication")
    return version

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    for name in ["version", "check", "fingerprint", "gate"]:
        command = commands.add_parser(name)
        command.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
        if name == "version":
            command.add_argument("--expect", help="validate packaging override equals repository version")
        if name == "check":
            command.add_argument("--write", action="store_true", help="regenerate the Go version default")
        if name == "gate":
            command.add_argument("--acceptance", help="acceptance JSON path; defaults to repository owner record")
    args = parser.parse_args()
    try:
        root = args.root.resolve()
        if args.command == "version":
            value = read_version(root)
            if args.expect is not None and semver(args.expect) != value:
                raise ReleaseError("packaging VERSION override does not match repository VERSION")
        elif args.command == "check":
            value = check_default(root, args.write)
        elif args.command == "fingerprint":
            value = fingerprint(root)
        else:
            value = gate(root, args.acceptance)
        print(value)
        return 0
    except (ReleaseError, ValueError):
        error = sys.exc_info()[1]
        print("release validation failed: " + str(error), file=sys.stderr)
        return 1

if __name__ == "__main__":
    sys.exit(main())
